apiVersion: v1
kind: Service
metadata:
  name: workday-counter
spec:
  type: LoadBalancer
  # loadBalancerIP: 192.168.111.40
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: workday-counter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workday-counter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workday-counter
  template:
    metadata:
      labels:
        app: workday-counter
    spec:
      containers:
      - name: workday-counter
        image: registry.opensuse.org/home/kukuk/container/container/workday-counter:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: MESSAGE
          value: Days of homeoffice:
