apiVersion: v1
kind: Service
metadata:
  name: workday-counter
spec:
  type: LoadBalancer
  loadBalancerIP: 10.162.233.66
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: workday-counter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workday-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workday-counter
  template:
    metadata:
      labels:
        app: workday-counter
    spec:
      containers:
      - name: workday-counter
        image: registry.opensuse.org/home/kukuk/container/container/workday-counter:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: TITLE
          value: "Homeoffice Days"
        - name: MESSAGE
          value: "Survived working days in homeoffice"
        - name: WORKDAYS_LABEL
          value: "Workdays"
        - name: STARTDATE_LABEL
          value: "Since"
        - name: STARTDATE
          value: "2020-03-13"
        - name: ENDDATE_LABEL
          value: "Today"
        #- name: ENDDATE
        #  value: "2020-0X-XX"
