apiVersion: v1
kind: Service
metadata:
  name: workday-counter
spec:
  type: LoadBalancer
  loadBalancerIP: 10.162.233.66
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: workday-counter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workday-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workday-counter
  template:
    metadata:
      labels:
        app: workday-counter
    spec:
      containers:
      - name: workday-counter
        image: registry.opensuse.org/home/kukuk/container/container/workday-counter:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: TITLE
          value: "Homeoffice Days Germany"
        - name: MESSAGE
          value: "Survived working days in homeoffice"
	- name: COUNTRY
	  value: "Germany"
	- name: STATE
	  value: "Bayern"
	- name: WORKDAYS_TITLE
          value: "Remaining (Germany, best guess)"
        - name: WORKDAYS_LABEL
          value: "Workdays"
        - name: STARTDATE_LABEL
          value: "Today"
        #- name: STARTDATE
        #  value: "2020-03-13"
        - name: ENDDATE_LABEL
          value: "Until"
        - name: ENDDATE
          value: "2020-04-30"
	- name: COUNTRY1
	  value: "Germany"
	- name: STATE1
	  value: "Bayern"
	- name: WORKDAYS1_TITLE
          value: "Germany"
        - name: WORKDAYS1_LABEL
          value: "Workdays"
        - name: STARTDATE1_LABEL
          value: "Since"
        - name: STARTDATE1
          value: "2020-03-13"
        - name: ENDDATE1_LABEL
          value: "Today"
        #- name: ENDDATE1
        #  value: "2020-0X-XX"
	- name: COUNTRY2
	  value: "China"
	#- name: STATE2
	#  value: ""
        - name: WORKDAYS2_TITLE
          value: "China"
        - name: WORKDAYS2_LABEL
          value: "Workdays"
        - name: STARTDATE2_LABEL
          value: "Since"
        - name: STARTDATE2
          value: "2020-02-03"
        - name: ENDDATE2_LABEL
          value: "Today"
        #- name: ENDDATE2
        #  value: "2020-0X-XX"
